### ISSUE TITLE
Problem when deparsing query with renamend Columns

### ISSUE THREAD

**Issue by primeapple** [lfittl/pg_query#128]
Hi, another one:

We have an original query like:
```sql
SELECT id as "new Test Id" from student
```
When we parse and deparse it, we get:
```sql
SELECT "id" AS new Test Id FROM "student"
```
which is not parsable anymore.

Bonus:
The queries:
```sql
SELECT id AS "TEST" from student
```
and
```sql
SELECT id AS TEST from student
```
are NOT the same, since the column is named `TEST` in the first one and `test` in the second one.

The problem is, that **quote signs are removed when deparsing the query** which is bad. There are multiple other situations, where this produces problems

**Comment by lfittl** [comment]
Fixed by https://github.com/lfittl/pg_query/commit/100a0c57b775b85056ef5a2367da43e567b5a3ab

Note that this tries to determine when escaping is needed (anytime an identifier is not `\w+`, or a keyword), and applies it only in such cases. There isn't a good way to get back to the way this was specified originally in the parse string, since we work with the the post-parse AST that doesn't keep the original text for each scan fragment.
