### ISSUE TITLE
Heroku deployment (flex missing)

### ISSUE THREAD

**Issue by mme** [lfittl/pg_query#31]
Heroku deployment is a bit painful at the moment (needs a custom buildpack).

Would it be reasonable to drop the flex requirement by providing a pregenerated scan.c file together with the downloaded source code?

**Comment by lfittl** [comment]
I think thats reasonable, it would be nice to use it without needing the custom build pack.

However this might take a bit, since in order to do it cleanly I'd want to do it after #24 is done. I've been meaning to change the current approach of using a forked Postgres (mostly for the JSON output functions), to using upstream postgres + patch series.

As part of that I can see adding pre-generated scan.c/gram.c files that are used if flex/bison are not installed. I'll see what I can do & update you once I've made progress :)
