### ISSUE TITLE
Build SQL from AST

### ISSUE THREAD

**Issue by jacobwgillespie** [lfittl/pg_query#4]
Is it possible to take the parse tree and build a SQL statement?  My use case is renaming tables (like, scanning for each time a relation is named and prepending a prefix).  It seems like it might be possible since normalize is able to rewrite the query, but I'm not sure.

**Comment by lfittl** [comment]
Technically there is parts of Postgres that can do this, specifically inside `postgres_fdw`
https://github.com/postgres/postgres/blob/master/contrib/postgres_fdw/deparse.c

Since pg_query has access to all of postgres that doesn't require catalog access, it might be possible to add this as a feature - but its a good amount of work for sure.

I'll keep it in my mind and might hack on this when I find the time, in any case feel free to hack on it yourself and submit a PR / ask for feedback :)

**Comment by jacobwgillespie** [comment]
Cool.  For now, I realized that the AST includes a position field, so I'm using that to do string replacements of the table names.  But I'll likely have a use for AST to query at some point, so I may take a stab at it.

All this is for https://github.com/playlist-media/turboquery, which is designed to take queries that execute against a Postgres database (like on RDS) and automate the transfer of data to Amazon Redshift, execution of the query at Redshift, and transfer back to Postgres.  It does some basic rewriting of the query to ensure it works on Redshift.  Far from complete, but we're looking to put it into production at Playlist.  Some complex queries are seeing around a 200x speedup using this approach.

So, all in all, thanks for the awesome gem!  It's proving very useful.  :smile:

**Comment by lfittl** [comment]
Nice, that looks like an awesome tool, and using substitutions using the positions in the AST sounds like a good approach :)

I've taken another look, and it looks like the best AST-to-SQL approach might be to just implement the deparsing of the AST in Ruby, since Postgres' own logic is a bit incomplete except for the most basic cases - and its quicker to write this in Ruby anyway.

In case you do come back to that route feel free to give me a shout, I might be able to find some time to help out & implement the basic support.

**Comment by lfittl** [comment]
@jacobwgillespie I'm experimenting with some basic support of this, see the spec for whats supported:

https://github.com/lfittl/pg_query/blob/master/spec/lib/deparse_spec.rb

I'll continuously expand this, is there a specific set of SQL that would need to be supported so this is useful to you? (e.g. all variants of `SELECT`)

**Comment by jacobwgillespie** [comment]
Hey!  Sorry, late reply.  What I'm modifying are `SELECT` statements and `INSERT INTO table SELECT` statements.  Thanks, looking awesome!

**Comment by lfittl** [comment]
@jacobwgillespie Just released 0.6.0 version of the gem which has deparsing support & should solve your use case :)

**Comment by jacobwgillespie** [comment]
:+1: Thanks!
