### ISSUE TITLE
CTE names are included in tables list

### ISSUE THREAD

**Issue by jcoleman** [lfittl/pg_query#52]
Currently the following query:
```
WITH cte_name AS (
    SELECT 1
)
SELECT *
FROM table_name, cte_name
```
parses and `#tables` returns `["cte_name", "table_name"]`.

I propose either:
1. `#tables` should return `["table_name"]` only, or
2. `#tables` should remain as is and a new method `#cte_names` should return the list of CTE aliases

Would you be interested in a PR with one of the above solutions?

**Comment by lfittl** [comment]
@jcoleman Thats a good question - the intent here was probably to get actual relations (i.e. tables/views), rather than CTEs.

Maybe the best way would be change the `#tables` behavior to exclude CTEs, but still add `#cte_names` in case someone needs that (so you could effectively use `q.tables + q.cte_names` in case you wanted both).

PR would be very welcome :)

**Comment by lfittl** [comment]
Actually, if you are feeling motivated on this topic - it might be nice to traverse into nested SELECTs as well, i.e. fix https://github.com/lfittl/pg_query/issues/38

I can also do that as a follow-up PR, about time that that issue gets fixed.

**Comment by lfittl** [comment]
@jcoleman Ended up fixing this in https://github.com/lfittl/pg_query/commit/7eb92cb868b0d9909a4d6d1320ef9e1da231d21a

Would be great if you could test it and let me know if there's any further improvements you think would help. I'll probably release 0.11.0 in a few days :)

**Comment by jcoleman** [comment]
That fixes it for me.

Side note: I had to update bundler to 1.12.5 to be able to use the gem by referencing a git ref...apparently there were issues with git ref + native extensions prior to that: https://github.com/bundler/bundler/issues/4106
