### ISSUE TITLE
Question: Any examples of warnings?

### ISSUE THREAD

**Issue by purcell** [lfittl/pg_query#7]
Hi! We've released [sqlint](https://github.com/purcell/sqlint), which is built on `pg_query` -- thanks so much for your awesome work!

I noticed that the parse results contain a `warnings` array, which we don't yet use -- do you have any examples of queries which cause `warnings` to be populated? Most of the PG warnings I've come across are issued only when queries are actually executed. Thanks!

**Comment by lfittl** [comment]
Awesome - great work! :+1:

Very happy to see you using pg_query there, this is exactly the kind of tools its made for :)

`warnings` would be populated if any part of the query was successfully parsed, but its Postgres-internal AST representation could not be converted to JSON.

This used to be a much larger issue, but since I automated this process (https://github.com/pganalyze/pg_query-outfuncs-generator) the output code should have 100% coverage.

See https://github.com/pganalyze/postgres/commit/f455ee802caf53b5e404187edfe31437e1c90d98#diff-7593043b7e3602e4c204b909c18087b7R1006 for where the warning is emitted.

As said, I don't think you have to support this - if you want to you can treat it the same as a syntax error, since you probably will have an empty parse tree for this query.

Closing this issue - but please don't hesitate to drop me a line anytime (lukas@fittl.com)

Cheers! :smile:

**Comment by purcell** [comment]
Ah, I see. Thanks!

I might end up sending a PR in due course, because I'd like to have a version of `tables()` and `filter_columns()` which returns the locations along with the table/column names. The idea would be to (optionally) live-connect to the DB while linting and print warnings if queries appear to reference nonexistent tables/columns. (I think it might end up quite complex in all but simple cases...)

Cheers, and thanks again.

**Comment by lfittl** [comment]
Sure thing, please feel free to send any PRs that make your life easier :)

pg_query is actively used by pganalyze (our hosted Postgres monitoring dashboard), so I might be a bit careful with things that break API, but the case you propose sounds reasonable :+1:

**Comment by purcell** [comment]
Yep, I'd plan to provide `tables_with_locations` or something like that, and keep all the existing tests passing.

**Comment by lfittl** [comment]
:+1: :tada:
